name: Deploy Insight Backoffice

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build App
        run: |
          npm ci
          npm run build:dev

      - name: Deploy to server (development)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/dev/angular-insight-backoffice
            git stash
            git checkout dev
            git pull
            npm install
            npm run build:dev
            cp -rf ./dist/. /usr/share/nginx/html/dev/backoffice

  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build App
        run: |
          npm ci
          npm run build:staging

      - name: Deploy to server (staging)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/staging/angular-insight-backoffice
            git stash
            git checkout staging
            git pull
            npm install
            npm run build:staging
            cp -rf ./dist/. /usr/share/nginx/html/staging/backoffice

  deploy-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build App
        run: |
          npm ci
          npm run build:prod

      - name: Deploy to server (production)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/angular-insight-backoffice
            git stash
            git checkout main
            git pull
            npm install
            npm run build:prod
            cp -rf ./dist/. /usr/share/nginx/html/backoffice
